# Generated by Django 4.2.11 on 2024-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='auteur',
            field=models.CharField(default=1, help_text='Auteur', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(default=1, upload_to='média'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default=1, upload_to='média'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='nom_client',
            field=models.CharField(default='', help_text='Nom du client', max_length=200),
            preserve_default=False,
        ),
    ]
