# Generated by Django 4.2.11 on 2024-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_portfolio_auteur_portfolio_image1_portfolio_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
