# Generated by Django 4.2.11 on 2024-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_remove_portfolio_fichier_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=500),
        ),
    ]
