# Generated by Django 4.2.11 on 2024-03-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0008_rename_description_portfolio_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='messages',
            new_name='description',
        ),
    ]
