# Generated by Django 4.2.11 on 2024-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0010_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videos',
            new_name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='video1',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video2',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
