# Generated by Django 4.2.11 on 2024-03-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(help_text='Nom du client', max_length=200)),
                ('tittre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image1', models.ImageField(upload_to='média')),
                ('image2', models.ImageField(upload_to='média')),
                ('description', models.TextField(default='')),
                ('auteur', models.CharField(help_text='Auteur', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
