# Generated by Django 4.2.11 on 2024-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fichier_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
